### General get api

GET http://localhost:3000

### Get all the products

GET http://localhost:3000/api/products

### Get a product by ID

GET http://localhost:3000/api/products/6753ecfa941ff73ac90011f7

### Insert a new product

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Product4",
    "quantity": 45,
    "price": 19.99
}

### Update an existing product with an ID

PUT http://localhost:3000/api/products/6754094b025e62dc08bf6e19
Content-Type: application/json

{
    "price": 21.99
}

### Delete an existing Product

DELETE http://localhost:3000/api/products/6754094b025e62dc08bf6e19